apiVersion: v1

services: 
  php-env:
    build:
    volume:
    - ./src:/var/www/html
    ports:
    - 8100:80
kind: Pod
metadata:
  name: rampa
spec:
  containers:
    - name: rampa
      image: rifki363/rampa:1.2
      ports:
        - containerPort: 80
    - name: rampa-mysql
      image: rifki363/rampa-mysql:1.2
      ports:
        - containerPort: 3306